# Generated by Django 4.1.3 on 2022-12-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragent_mod',
            options={'verbose_name': 'User Agent', 'verbose_name_plural': 'Users Agents'},
        ),
    ]
