# Generated by Django 4.1.3 on 2022-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent_mod',
            name='manage_properties',
        ),
    ]
