# Generated by Django 4.1.3 on 2022-12-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragent_mod',
            options={'verbose_name': 'Admin - Agent -User', 'verbose_name_plural': 'Admins - Agents- Users'},
        ),
    ]
