# Generated by Django 4.1.3 on 2022-12-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0006_remove_property_mod_user_agent'),
        ('user_agent_app', '0002_alter_useragent_mod_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent_mod',
            name='manage_properties',
        ),
        migrations.AddField(
            model_name='useragent_mod',
            name='manage_properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manage_properties', to='property_app.property_mod'),
        ),
    ]
