# Generated by Django 4.1.3 on 2022-12-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0009_remove_property_mod_nuevo_campo'),
        ('user_agent_app', '0004_remove_useragent_mod_manage_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent_mod',
            name='manage_properties',
            field=models.ManyToManyField(blank=True, related_name='manage_properties', to='property_app.property_mod'),
        ),
    ]
