# Generated by Django 4.1.3 on 2022-12-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_and_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(blank=True, null=True, upload_to='photos_properties')),
            ],
        ),
        migrations.CreateModel(
            name='Location_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=4, verbose_name='Operation Type')),
                ('title', models.CharField(max_length=200, verbose_name='Property Title')),
                ('type', models.CharField(choices=[('flat', 'Flat'), ('area', 'Area'), ('chalet', 'Chalet'), ('shop', 'Comercial'), ('offices', 'Offices')], max_length=7, verbose_name='Property Type')),
                ('state', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=4, verbose_name='Property state')),
                ('price', models.PositiveIntegerField(verbose_name='Property Price')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property_app.address_mod', verbose_name='Address Property')),
            ],
        ),
    ]
