# Generated by Django 4.1.3 on 2022-12-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_app', '0002_initial'),
        ('user_agent_app', '0001_initial'),
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_mod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_agent_app.useragent_mod'),
        ),
        migrations.AddField(
            model_name='property_mod',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner_app.owner_mod'),
        ),
        migrations.AddField(
            model_name='images_mod',
            name='to_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.property_mod'),
        ),
        migrations.AddField(
            model_name='city_mod',
            name='city_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.location_mod'),
        ),
        migrations.AddField(
            model_name='address_mod',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.city_mod'),
        ),
        migrations.AddField(
            model_name='address_mod',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.location_mod'),
        ),
    ]
