# Generated by Django 4.1.3 on 2022-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_mod',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
