# Generated by Django 4.1.3 on 2022-12-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_mod',
            old_name='created_by',
            new_name='user_agent',
        ),
    ]
