# Generated by Django 4.1.3 on 2022-12-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0002_initial'),
        ('property_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_mod',
            old_name='addres',
            new_name='address',
        ),
        migrations.AddField(
            model_name='property_mod',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner_app.owner_mod'),
        ),
    ]
