# Generated by Django 4.1.3 on 2022-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0003_alter_property_mod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_mod',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='property_mod',
            name='type',
            field=models.CharField(choices=[(None, 'Choose the type'), ('flat', 'Flat'), ('area', 'Area'), ('chalet', 'Chalet'), ('shop', 'Comercial'), ('offices', 'Offices')], max_length=7, verbose_name='Property Type'),
        ),
    ]
