# Generated by Django 4.1.3 on 2022-12-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0004_alter_property_mod_slug_alter_property_mod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_mod',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.city_mod'),
        ),
        migrations.AlterField(
            model_name='address_mod',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_app.location_mod'),
        ),
        migrations.AlterField(
            model_name='property_mod',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.address_mod', verbose_name='Address Property'),
        ),
        migrations.AlterField(
            model_name='property_mod',
            name='type',
            field=models.CharField(choices=[('flat', 'Flat'), ('area', 'Area'), ('chalet', 'Chalet'), ('shop', 'Comercial'), ('offices', 'Offices')], max_length=7, verbose_name='Property Type'),
        ),
    ]
