# Generated by Django 4.1.3 on 2022-12-14 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_app', '0006_remove_property_mod_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_mod',
            name='user_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
