# Generated by Django 4.1.3 on 2022-12-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0008_property_mod_nuevo_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_mod',
            name='nuevo_campo',
        ),
    ]
